#!/bin/bash
`dirname $0`/volume-pre | python3 -c '
val = input();
if val == "MUTE":
    print("🔇 ")
else:
    num = int(val[:-1])
    if num > 67:
        print("🔊", val)
    elif num > 33:
        print("🔉", val)
    else:
        print("🔈", val)
'
